### ISSUE TITLE
Installation error on Visual Studio 2017

### ISSUE THREAD

**Issue by fjch1997** [Guzzter/ImageToolsVSExtension#1]
![image](https://cloud.githubusercontent.com/assets/9412032/25981341/9f9b0cf6-36a2-11e7-9fa7-f6946ef1b50d.png)

.vsix file was downloaded directly from Visual Studio Marketplace.

Version info. 

![image](https://cloud.githubusercontent.com/assets/9412032/25981379/d7cf378c-36a2-11e7-94c3-d44bf4dc3307.png)

Really want this to work. It seems like a nice plugin

**Comment by jordyjanssen** [comment]
Same issue with the Community edition:
![afbeelding](https://cloud.githubusercontent.com/assets/14125506/26577390/922163b6-452c-11e7-9589-f18b6b7c4b26.png)
Or could you elaborate on which prerequisites I'm missing?

**Comment by fjch1997** [comment]
When I looked into the source, these prerequisites are defined

```
<Prerequisites>

    <Prerequisite Id="Microsoft.VisualStudio.Component.CoreEditor" Version="[15.0,16.0)" DisplayName="Visual Studio core editor" />

    <Prerequisite Id="Microsoft.VisualStudio.Component.DiagnosticTools" Version="[15.0.25814.0,16.0)" DisplayName="Profiling tools" />

    <Prerequisite Id="Microsoft.VisualStudio.Shell.12.0" Version="[12.0]" />

  </Prerequisites>
```

They seems to be just the normal essential VS components but due to the lack of knowledge on VS Extensions development I can't seem to find a solution. Simply removing them does not work

**Comment by Guzzter** [comment]
I have made a fix, only I have a problem with updating the extension in the marketplace. I am waiting on Microsoft support for helping resolving this issue.

**Comment by Guzzter** [comment]
Solved with new version, now on Marketplace. Please have a look and let me know if it works/fails.

Thanks for reporting this issue.
